// <auto-generated />
namespace Inlämningsuppgift_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial12334343 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial12334343));
        
        string IMigrationMetadata.Id
        {
            get { return "201901171246267_initial12334343"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
